name: Updated Go Workflow
on:
  workflow_call:
    inputs:
      SHA:
        required: true
        type: string
        default: ''
permissions: read-all
jobs:
  updated-job:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      if: ${{ inputs.SHA}}
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.SHA }}
    - run: echo 'Hello from PR in danimartin-dev ///////////////// '
    - run: echo $GITHUB_SHA ${{ inputs.SHA }}
