name: Seed Job
on:
  pull_request:
    types: [review_requested]
permissions: read-all
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'From fork'
  call-seed-job:
    # if: github.event.review.state == 'approved' && github.event.review.body == 'Run seed job'
    # Update this path to test your workflow. ie. {owner}/{repo}/.github/workflows/seed-job-new-file.yml@{branch}
    #uses: danimartin-dev/testing-restrictions/.github/workflows/seed-job-new-file.yml@dev
    uses: ./.github/workflows/seed-job-new-file.yml
