name: Seed Job
on:
  pull_request_review:
    types: [submitted]
permissions: read-all
jobs:
  call-seed-job:
    if: github.event.review.state == 'approved' && github.event.review.body == 'Run seed job'
    uses:  danimartin-dev/testing-restrictions/.github/workflows/seed-job-new-file.yml@dev
    with:
      SHA: '12345'
