name: Seed Job
on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  # workflow_dispatch:
  #   inputs:
  #     SHA:
  #       description: 'GitHub SHA'
  #       required: true
  #       default: ''
permissions: read-all
jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Seed Job
        run: echo 'Running seed job for new/updated workflow...'
      - run: echo ${{ github.event.issue.user.site_admin }}
  call-seed-job:
    #if: github.event.review.state == 'approved'
    uses:  ./.github/workflows/seed-job-new-file.yml
    # with:
    #   SHA: ${{ github.event.inputs.SHA }}
